on: [push]
name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          npm ci
          npm run build
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Chekout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm run start
